name: Update README with LeetCode Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at 12:00 UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Requests Python Package
        run: pip install requests

      - name: Update README with LeetCode stats and Badge
        run: |
          python - <<END
          import requests
          import json

          # Fetch LeetCode stats
          response = requests.get('https://leetcodestats.cyclic.app/antoinebou13')
          stats = json.loads(response.text)

          # Generate badge URLs
          total_solved_badge = f"https://img.shields.io/badge/Total_Solved-{stats['totalSolved']}%2F{stats['totalQuestions']}-blue"
          easy_solved_badge = f"https://img.shields.io/badge/Easy_Solved-{stats['easySolved']}%2F{stats['totalEasy']}-green"
          medium_solved_badge = f"https://img.shields.io/badge/Medium_Solved-{stats['mediumSolved']}%2F{stats['totalMedium']}-yellow"
          hard_solved_badge = f"https://img.shields.io/badge/Hard_Solved-{stats['hardSolved']}%2F{stats['totalHard']}-red"

          # Read existing README.md
          with open('README.md', 'r') as f:
            content = f.read()

          # Add the badges in a summary/details section
          new_content = f"<details>\n<summary>:trophy: LeetCode Stats</summary>\n"
          new_content += f"![Total Solved]({total_solved_badge})\n"
          new_content += f"![Easy Solved]({easy_solved_badge})\n"
          new_content += f"![Medium Solved]({medium_solved_badge})\n"
          new_content += f"![Hard Solved]({hard_solved_badge})\n</details>\n"

          # Append to existing content
          new_content += content

          # Write new README.md
          with open('README.md', 'w') as f:
            f.write(new_content)
          END

      - name: Commit and push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add -A
          git commit -m "Automatically update README with LeetCode stats and Badges"
          git push
